1. Challenge 1:
  - Answer: La respuesta es la "b"
  - Explanation: El primer console.log retorna "xyz" porque la función es invocada y el segundo console.log retorna "xyz" porque la variable "foo" cambió dentro de la función. No se genera error porque la variable es declarada fuera. Si se intentase declarar primero fuera y después dentro de la función, se generaría un error.


2. Challenge 2:
  - Answer: La respuesta es la "c" 
  - Explanation: Primero retorna el console.log dentro de la función, llamando a la variable de dentro y después el console.log fuera de la función llama a la variable que está fuera de la función.


3. Challenge 3:
  - Answer: La respuesta es la "c"
  - Explanation: La respuesta es la "c" porque no importa cuando se invoque  la función siempre y cuando esté declarada, ya sea antes o después.


4. Challenge 4:
  - Answer: La respuesta es "b"
  - Explanation: La respuesta es "b" porque si "b" es igual a "a", en el cambio de variable de "b.num=90" está haciendo referencia a que el objeto de b cambia a 90, entonces si b es igual "a", "a" es 90.


5. Bonus - Challenge 5:
  - Answer: La respuesta es la "c"
  - Explanation:
